apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args: ['echo $WHO_SAID said "\"$WHAT_WAS_SAID\""; sleep infinity']
          envFrom:
            - secretRef:
                name: gossip
